### ISSUE TITLE
Fix akeyless bug that prevents releases and release failed build

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/rainbowkit-celo#106]
Hey @pputman12, the automatic release flow in this repo [celo-org/rainbowkit-celo](https://github.com/celo-org/rainbowkit-celo) seems to have broken at the "[Akeyless Get Secrets" step](https://github.com/celo-org/rainbowkit-celo/actions/runs/7658298518/job/20870908628#step:5:8).

```sh
Error: can't get secret value: %!w(string={"error":"failed to get the value of the requested secrets: Desc: failed to obtain secret access credentials, Error: Desc: Failed to get secret access creds. Status 401 Unauthorized, Error: UnauthorizedAccess. Message: account id: acc-2gyt10uq3as8, access id: p-kf9vjzruht6l. unauthorized access for access id p-kf9vjzruht6l"}
)
```

Probably a relatively simple permissions issue. Could you help me fix the bug?

**Priority**: Not urgent, I'd say in the next 1-2 weeks is fine. The only impact this has is that a demo website (at [rainbowkit-with-celo.vercel.app](https://rainbowkit-with-celo.vercel.app/)) cannot be deployed in the mean time. I made a small patch that failed to be deployed here: 
- https://github.com/celo-org/rainbowkit-celo/pull/103

**Comment by arthurgousset** [comment]
Fixed by: 
- https://github.com/celo-org/rainbowkit-celo/pull/100

**Comment by arthurgousset** [comment]
I'm not sure this is fixed, the workflow related to the PR broke: 
- https://github.com/celo-org/rainbowkit-celo/actions/runs/7742517634

Or am I missing something?

**Comment by pputman-clabs** [comment]
No this is due to the branch restriction I setup which apparently isn't working.  fixed now, I'll figure out whats wrong with the subclaims.

**Comment by arthurgousset** [comment]
Hey @pputman-clabs the same "[Akeyless Get Secrets" step](https://github.com/celo-org/developer-tooling/actions/runs/7744610057/job/21118722738#step:5:8) is broken in the [celo-org/developer-tooling](https://github.com/celo-org/developer-tooling) repo.

For example, this workflow in this PR:
- https://github.com/celo-org/developer-tooling/pull/93
- https://github.com/celo-org/developer-tooling/actions/runs/7744610057/job/21118722738

**Comment by pputman-clabs** [comment]
Access role was overwritten, fixed now.

**Comment by pputman-clabs** [comment]
To document the issues, we recently added a branch protection so only certain branches would be able to access the secret.

This adds a branch=main subclaim to the access role.  This seems to have caused a problem where its not actually allowing the specified branch, so I've removed that restriction.  I'll have to retest and see what subclaims the OIDC token is sending from github, to see why its not matching and running properly.

**Comment by arthurgousset** [comment]
Thanks for the context, very useful 💯

**Comment by arthurgousset** [comment]
This PR fixed the `release` workflow, since the subsequent workflows ran without errors.

For example:
- [Merge pull request #100 from celo-org/pputman/update-key-path #28](https://github.com/celo-org/rainbowkit-celo/actions/runs/7742517634/job/21112219411)
- [extend base developer tooling renovate config (#109) #29](https://github.com/celo-org/rainbowkit-celo/actions/runs/7841997273/job/21399431569)

<img width="1142" alt="image" src="https://github.com/celo-org/rainbowkit-celo/assets/46296830/d2258064-c5f3-4b41-ab2b-27859a910ded">

On that basis, this ticket can be closed.
