### ISSUE TITLE
Attempted import error: 'celoCannoli' is not exported from 'viem/chains' (imported as 'celoCannoli').

### ISSUE THREAD

**Issue by Zagorodnyi** [celo-org/rainbowkit-celo#114]
It seems this chain is no longer available on viem/chains

**Comment by shazarre** [comment]
@Zagorodnyi cannoli network is no longer supported, here's [a list of available networks](https://docs.celo.org/network).

**Comment by Zagorodnyi** [comment]
> @Zagorodnyi cannoli network is no longer supported, here's [a list of available networks](https://docs.celo.org/network).

Importing anything from `packages/rainbowkit-celo/chains/index.ts` will cause the error from this issue.
Cannoli is still present in the rainbowkit codebase.

**Comment by arthurgousset** [comment]
Great catch @Zagorodnyi, that's our bad. I removed `Cannoli` from viem, but forgot to remove it here:
- https://github.com/wevm/viem/pull/1462

**Comment by arthurgousset** [comment]
Thanks for opening a PR 💯

**Comment by arthurgousset** [comment]
Thanks for opening a PR 💯
