### ISSUE TITLE
Cant Publish to NPM

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/rainbowkit-celo#121]
```
can't get secret value: %!w(string={"error":"failed to get the value of the requested secrets: Desc: failed to obtain secret access credentials, Error: Desc: Failed to get secret access creds. Status 401 Unauthorized, Error: UnauthorizedAccess. Message: account id: *REDACTED** access id: REDACTED unauthorized access for access id REDACTED"}
```

**Comment by aaronmgdr** [comment]
https://github.com/celo-org/rainbowkit-celo/actions/runs/8374883629

**Comment by pputman-clabs** [comment]
Removed main branch restriction on the secret that was causing problems.  Won't add these again unless I can get a confirmation someone will be available to test the workflows and make sure they're working properly.

**Comment by arthurgousset** [comment]
Ref: 
- https://github.com/celo-org/rainbowkit-celo/pull/123

**Comment by arthurgousset** [comment]
Patrick kindly fixed this
