### ISSUE TITLE
Update to new Celo branding

### ISSUE THREAD

**Issue by Deepcryptodive** [celo-org/rainbowkit-celo#21]
Hey folks!

Could all icons that are shown be updated to match the new Celo branding?
That would be amazing!

Guidelines can be found at: 
https://celo.org/brand-kit-symbol
https://celo.org/brand-kit-wordmark

Currently the old branding is still being used, which isn't consistent with the new Celo identity.

_Examples from GoodGhosting.com:_
![image](https://user-images.githubusercontent.com/61325205/213557164-4283c352-e3b5-463e-a3f6-fcf718591bc8.png)
![image](https://user-images.githubusercontent.com/61325205/213557239-2a195fd9-9f74-4ed5-a04b-f72159066788.png)

**Comment by aaronmgdr** [comment]
thanks for pointing this out. :)

**Comment by aaronmgdr** [comment]
@Deepcryptodive I have released 0.5.0 with the new branding.
