### ISSUE TITLE
Approve TXs prompts not showing up (received?) in Valora app

### ISSUE THREAD

**Issue by fodisi** [celo-org/rainbowkit-celo#58]
Hi all,
Francis from HaloFi here.
We have many users reporting connectivity issues w/ Valora and I Valora is rolling out v. 1.64.2 which is expected to fix some of these issues.
I updated my Valora to the latest (1.64.2 on iOS 15.7.8, iPhone 7 plus), and assuming the new valora version fixes it, I'm still unable to approve transactions with Valora using `rainbowkit-celo`. I was able to reproduce this issue with both HaloFi and the Demo site (https://rainbowkit-with-celo.vercel.app/fee-currency).

I also contacted the Valora team via Help >> Contact menu option to share the logs of my valora session on my cellphone - I hope you can also get access to that w/ the Valora team.

the issue basically is that users are able to connect the wallet (accessing sites via mobile or desktop), but when a transaction that requires an approval is submitted, the approval request is never displayed in Valora.

I attached a small video displaying the steps I did in the Demo page to reproduce the issue. note that the site just keeps displaying `Transaction sending` in the left bottom corner, but nothing happens and the tx approval never arrived in my Valora wallet (cellphone not shown in video but was close to me at time of testing).

I'm also attaching an error that was displayed in the console after leaving the demo page open waiting for the `Transaction sending` process timedout. The screenshot attached contains the errors logged at the timeout moment.

Let me know if there's any other test/info we can perform/share to help out.
Thanks

![image](https://github.com/celo-org/rainbowkit-celo/assets/36540281/a0e12c12-b45b-488e-b255-00366e21b287)

![image](https://github.com/celo-org/rainbowkit-celo/assets/36540281/0c986dc3-e01f-45d0-b773-44842192aeac)

**Comment by fodisi** [comment]
there's nothing major in the video, other than the steps.

https://github.com/celo-org/rainbowkit-celo/assets/36540281/bec77989-9f00-47b8-9609-6ddb29eee1ff

**Comment by aaronmgdr** [comment]
fairly certain this will be cause by something further down in the stack as this package is just configs. but will double check that

**Comment by aaronmgdr** [comment]
sorry, we have a few conflicting priorities (and i believe valora looked into this) please let me know if there is still an issue or if you have found resolution
