### ISSUE TITLE
Fix automatic npm release of `@celo/rainbowkit-celo`

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/rainbowkit-celo#64]
Currently the automatic npm release of `@celo/rainbowkit-celo` is broken due to a faulty npm auth token. 
As far as I understand, `rainbowkit-celo` can also not be released manually.

That means this bug currently blocks any new npm releases of `@celo/rainbowkit-celo`.

This is done
- if the automatic npm release process works again (preferred), or
- if `rainbowkit-celo` can be released manually (less preferred).

**Comment by pputman-clabs** [comment]
It looks like someone added 2fa with a yubikey to the app-tooling npmjs account so I can't login, I'll need someone to give me access or create a new token.

**Comment by pputman-clabs** [comment]
Nicolas is helping me with this since he has access

**Comment by pputman-clabs** [comment]
<img width="460" alt="image" src="https://github.com/celo-org/rainbowkit-celo/assets/99900942/d29ef55a-e1c5-4c2a-bfab-eb7da83934ed">
Nicolas was able to create a new token and add it to our secrets manager, and is now publishing.

**Comment by 0xarthurxyz** [comment]
Thanks @pputman-clabs !
