### ISSUE TITLE
Try the new wagmi@beta and test the fee currency support

### ISSUE THREAD

**Issue by nicolasbrugneaux** [celo-org/rainbowkit-celo#67]

**Comment by nicolasbrugneaux** [comment]
After experimenting quite a bit and getting my hands dirty, it's safe to say the alpha is not **ready** and we should table that issue for now.

Outside of "cosmetic" changes (such as renaming the Provider and Context and some minor signatures), they also changed the way to declare which wallet connectors to use and that affects both rainbowkit and rainbowkit-celo. So will wait for documentation because [the alpha one](https://alpha.wagmi.sh/react/getting-started) is very much in progress 

![Image](https://github.com/celo-org/rainbowkit-celo/assets/3650621/c2336250-c36a-47d9-8987-f7001b39d7c6)



cc @0xarthurxyz

**Comment by nicolasbrugneaux** [comment]
Leaving this as blocked

**Comment by 0xarthurxyz** [comment]
Looks like we might be unblocked, [wagmi v2 alpha](https://x.com/wagmi_sh/status/1707476847351468334?s=20) is out it seems

<img width="450" src="https://github.com/celo-org/rainbowkit-celo/assets/46296830/2caab446-c2d1-40c8-ac28-7c96bd455032">

**Comment by nicolasbrugneaux** [comment]
Still very alpha, haven't managed a proper working example app

**Comment by nicolasbrugneaux** [comment]
As of  `2.0.0-alpha.10`, the feecurrency feature is still not a thing as far as my trials go. Will reach out to their team to figure out if that's a me issue

**Comment by 0xarthurxyz** [comment]
[Looks like](https://twitter.com/wagmi_sh/status/1719817669073846363) they are at wagmi beta now: [https://beta.wagmi.sh](https://t.co/S5JKbeikET)

![Image](https://github.com/celo-org/rainbowkit-celo/assets/46296830/6f15e53d-0d2b-489f-9024-a8f79c408f40)

> Will reach out to their team to figure out if that's a me issue

Do they know about our fee currency issue?

**Comment by aaronmgdr** [comment]
https://github.com/celo-org/react-celo/issues/364

**Comment by 0xarthurxyz** [comment]
Wagmi 2.0 is in production (out of alpha and beta): https://github.com/wevm/wagmi/releases/tag/wagmi%402.0.3

**Comment by aaronmgdr** [comment]
I confirmed that 

```
  const config = useConfig()
  const { data: hash, sendTransaction } = useSendTransaction({config: {...config, chains: [celo]}})
  const sendIt = () => {
    sendTransaction({
      feeCurrency: cUSDAddress.data,
      value: BigInt(100000000),
      to: '0x22579CA45eE22E2E16dDF72D955D6cf4c767B0eF',
  })

```

sends the request with fee currency all the way to 

```

client.request({
            method: 'eth_sendTransaction',
            params: [request],
```

note that to get types working correctly i needed to set the celo chain on the config explicitly


`useWriteContract` also worked perfectly
