### ISSUE TITLE
Update for RainbowKit v2

### ISSUE THREAD

**Issue by jmrossy** [celo-org/rainbowkit-celo#84]
Wagmi + Viem v2 are live. Rainbowkit has published a v2 beta to match it. 

Relevant docs:
https://beta.rainbowkit.com/guides/rainbowkit-wagmi-v2
https://viem.sh/docs/migration-guide#2xx-breaking-changes
https://wagmi.sh/react/guides/migrate-from-v1-to-v2

**Comment by jmrossy** [comment]
Alternatively, it may be better to just get the wallets added to rainbowkit's official list: https://github.com/rainbow-me/rainbowkit/tree/main/packages/rainbowkit/src/wallets/walletConnectors

Viem already has celo in its chain consts so the need for this package is diminished

**Comment by jmrossy** [comment]
Seems to work: https://github.com/jmrossy/celo-station/blob/wagmi-v2/src/config/wallets.ts

**Comment by aaronmgdr** [comment]
alternatively consider deprecating package as (as @jmrossy mentioned) the need for it has diminished and there has proved to be high maintenance costs for such a small config.

**Comment by arthurgousset** [comment]
Made a Github Discussion about this so we can reference it when making the PR in rainbowkit, if/when we deprecate this package, and for future reference:
- https://github.com/celo-org/rainbowkit-celo/discussions/85

**Comment by aaronmgdr** [comment]
Ive reached out to Valora and they are keen to add valora config direct to rainbowkit. 

for the other wallets terminal and ~celo wallet~ othello A confirm they actually work. and if need be make prs to rainbowkit

**Comment by jmrossy** [comment]
Othello Wallet doesn't support Wallet Connect anymore. It used a beta version of v2 that broke at some point and the lift to migrate it to the latest WC version is surprisingly high. It can be excluded.

**Comment by aaronmgdr** [comment]
closing as we will not be create a v2 config but instead ensuring all wallets that still work are in the official repo
