### ISSUE TITLE
Submit Celo-specific wallets in official rainbowkit repo

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/rainbowkit-celo#86]
Todo based on this Github Discussion:
- https://github.com/celo-org/rainbowkit-celo/discussions/85

> If I understand correctly, we can provide a similar developer experience if we add Celo-specific wallets to rainbowkit's ([`@rainbow-me/rainbowkit`](https://www.npmjs.com/package/@rainbow-me/rainbowkit)) official wallet list ([walletConnectors](https://github.com/rainbow-me/rainbowkit/tree/main/packages/rainbowkit/src/wallets/walletConnectors)).
> 
> As mentioned, [`viem`](https://www.npmjs.com/package/viem) already publishes Celo chain configs for mainnet ([`celo.ts`](https://github.com/wevm/viem/blob/main/src/chains/definitions/celo.ts)) and alfajores testnet ([`celoAlfajores.ts`](https://github.com/wevm/viem/blob/main/src/chains/definitions/celoAlfajores.ts)).
> 
> Seems like the next step is to make a PR to add Celo-specific wallets to rainbowkit, and see if it gets merged.

_Originally posted by @arthurgousset in https://github.com/celo-org/rainbowkit-celo/discussions/85#discussioncomment-8153720_
```[tasklist]
### Tasks
- [ ] Valora
- [x] Celo Terminal
- [x] Celo Wallet
- [ ] celo ledger app
```

**Comment by aaronmgdr** [comment]
maybe  @jeanregisser can help with valora

**Comment by arthurgousset** [comment]
(for future reference) 
Configured wallets are here: 

```ts
export { default as Valora } from "./valora.js";
export { default as CeloWallet } from "./celo-wallet.js";
export { default as CeloTerminal } from "./celo-terminal.js";
export { metaMaskWalletPlus as MetaMask } from "./metamask-with-fee-currency.js";
```

Source: [rainbowkit-celo/wallets/index.ts](https://github.com/celo-org/rainbowkit-celo/blob/main/packages/rainbowkit-celo/wallets/index.ts)

**Comment by aaronmgdr** [comment]
- Celo Wallet aka Othello No longer supports  wallet connect so ive marked as complete 
- Celo Terminal -- since the app doesnt have a deep link this connector never really worked as you had to copy and paste the wallet connect url by hand anyway. so the same functionality and experience exist with default wallet connect connector therefore mark as complete

**Comment by aaronmgdr** [comment]
next write a migration guide

**Comment by arthurgousset** [comment]
Brief ping @jeanregisser: is adding Valora to the official Rainbowkit [`walletConnectors`](https://github.com/rainbow-me/rainbowkit/tree/main/packages/rainbowkit/wallets) on your backlog? 

We are planning to stop maintaining `@celo/rainbowkit-celo` and suggest all wallets are added upstream in rainbowkit. In other words, this package is not needed anymore as far as we can see.

**Comment by bakoushin** [comment]
@arthurgousset Valora connector is added to Rainbow kit, as well as Celo/Alfajores chains:

https://github.com/rainbow-me/rainbowkit/releases/tag/%40rainbow-me%2Frainbowkit%402.1.6

**Comment by aaronmgdr** [comment]
🔥  oh baby when you merge like that...
